Models/PageBlock.cs
using System;

namespace RGCoaching.Models
{
    public class PageBlock
    {
        public Guid PageBlockId { get; set; }
        public Page Page { get; set; }
        public Block Block { get; set; }
        public Int32 Order { get; set; }
    }
}

Areas/Admin/Controllers/PageBlocksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RGCoaching.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RGCoaching.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrator")]
    [Area("Admin")]
    [Route("/[area]/[controller]/[action]")]
    public class PageBlocksController : Controller
    {
        private readonly RGCoachingDbContext _context;

        public PageBlocksController(RGCoachingDbContext context)
        {
            _context = context;
        }

        [HttpGet("/[area]/[controller]/Edit")]
        public IActionResult GetEdit([FromQuery] Guid pageBlockId, [FromQuery] Guid blockId)
        {
            Block block = _context.Blocks.SingleOrDefault(b => b.BlockId == blockId);
            if (block == null)
            {
                block = new Block();
            }
            PageBlock pageBlock = _context.PageBlocks.SingleOrDefault(pb => pb.PageBlockId == pageBlockId);
            if (pageBlock == null)
            {
                pageBlock = new PageBlock();
            }
            pageBlock.Block = block;
            return View("Edit", pageBlock);
        }

        [HttpPost("/[area]/[controller]/Edit")]
        public IActionResult PostEdit([FromForm] PageBlock pageBlock)
        {
            pageBlock.Page = _context.Pages.SingleOrDefault(p => p.PageId == pageBlock.Page.PageId);
            pageBlock.Block = _context.Blocks.SingleOrDefault(b => b.BlockId == pageBlock.Block.BlockId);
           _context.Update(pageBlock);
            _context.SaveChanges();
            return RedirectToAction(controllerName: "Blocks", actionName: "GetEdit", 
                                    routeValues: new { blockId = pageBlock.Block.BlockId });
        }

        [HttpGet]
        public IActionResult Delete([FromQuery] Guid pageBlockId)
        {
            PageBlock pageBlock = _context.PageBlocks.SingleOrDefault(pb => pb.PageBlockId == pageBlockId);
            _context.Remove(pageBlock);
            _context.SaveChanges();
            return RedirectToAction(controllerName: "Blocks", actionName: "List");
        }
    }
}

Areas/Admin/Views/PageBlocks/Edit.cshtml
@using RGCoaching.Models
@inject RGCoachingDbContext Context
@model PageBlock

@{
  ViewData["Title"] = "Admin - Blocs - Edition";
  ViewData["PageName"] = "Association d'un bloc";
  Layout = "/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container">
  <form asp-area="Admin" asp-controller="PageBlocks" asp-action="PostEdit">
    <div class="form-group">
      <label for="page-select">Page</label>
      <select asp-for="Page.PageId" id="page-select" class="form-control">
        @foreach (Page pageItem in Context.Pages)
        {
          <option value="@pageItem.PageId">@pageItem.Name</option>
        }
      </select>
    </div>
    <div class="form-group">
      <label for="block-name">Block</label>
      <select asp-for="Block.BlockId" id="block-select" class="form-control">
        @foreach (Block blockItem in Context.Blocks)
        {
          <option value="@blockItem.BlockId">@blockItem.Name</option>
        }
      </select>
    </div>
    <div class="form-group">
      <label for="page-url">Ordre</label>
      <input asp-for="Order" type="number" id="order-input" class="form-control"/>
    </div>
    <input type="hidden" asp-for="PageBlockId" />
    <input class="btn btn-success mb-2" type="submit" value="Sauvegarder" />
  </form>
</div>