Areas/Admin/Controllers/ClientController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RGCoaching.Models;

namespace RGCoaching.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrator")]
    [Area("Admin")]
    [Route("/[area]/[controller]/[action]")]
    public class ClientController : Controller
    {
        private readonly RGCoachingDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public ClientController(RGCoachingDbContext injectedContext,
                                UserManager<IdentityUser> userManager)
        {
            _context = injectedContext;
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult List()
        {
            return View(_context.Customers);
        }

        [HttpPost("/[area]/[controller]/Edit")]
        public IActionResult PostEdit([FromForm] Customer customer)
        {
            IdentityUser user = new IdentityUser
            {
                Email = customer.Email,
                UserName = customer.Email
            };
            _userManager.CreateAsync(user).Wait();
            _context.Update(customer);
            _context.SaveChanges();
            return View("List", _context.Customers);
        }

        [HttpGet("/[area]/[controller]/Edit")]
        public IActionResult GetEdit([FromQuery] Guid customerId)
        {
            Customer customer = _context.Customers.SingleOrDefault(customer => customer.CustomerId == customerId);
            if (customer == null)
            {
                customer = new Customer();
            }
            return View("Edit", customer);
        }

        [HttpGet]
        public IActionResult Delete([FromQuery] Guid customerId)
        {
            Customer customer = _context.Customers.Single(c => c.CustomerId == customerId);
            _context.Customers.Remove(customer);
            _context.SaveChanges();
            return View("List", _context.Customers);
        }
    }
}

Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.Extensions.Logging;
using RGCoaching.Data;
using RGCoaching.Models;

namespace RGCoaching.Controllers
{
    public class PagesController : Controller
    {
        private readonly RGCoachingDbContext _context;
       
        public PagesController(ILogger<PagesController> logger,
                              RGCoachingDbContext context)
        {
            _context = context;
        }

        [ActionName("ServePage")]
        [HttpGet("/[controller]/{*url}")]
        [HttpGet("/{url=index}")]
        public IActionResult ServePage(String url)
        {
            Models.Page page = _context.Pages.SingleOrDefault(
                p => p.Url.ToLower() == url.ToLower()
            );
            if (page == null)
            {
                return NotFound();
            }
            page.PageBlocks = _context.PageBlocks.Include(pb => pb.Block)
                                                 .Where(pb => pb.Page.PageId == page.PageId)
                                                 .ToList();
            return View(page);
        }
    }
}

Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">

    <!-- Begin CSS Files -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" href="~/assets/css/dashboard.css" type="text/css" />

    <!-- Scripts Files -->
    <script src="~/assets/js/font-awesome/font-awesome.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs="
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Bootstrap Date-Picker Plugin -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css" />

    <title>@ViewData["Title"]</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>

<body>

  <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">RG Coaching Admin</a>
    <a class="btn btn-outline-light" asp-controller="Home" asp-action="Index">Quitter</a>
  </nav>

  <div class="container-fluid">
    <div class="row">
      <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
              <ul class="nav flex-column">

                  <li class="nav-item">
                      <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                          <a class="d-flex align-items-center text-muted">Pages</a>
                      </h6>
                      <ul class="list-unstyled" id="programs-submenu">
                          <li class="nav-item">
                              <a asp-area="Admin" asp-controller="Pages" asp-action="List"
                                 class="nav-link">
                                  <i class="fa fa-list"></i>Lister
                              </a>
                          </li>
                          <li class="nav-item">
                              <a asp-area="Admin" asp-controller="Pages" asp-action="GetEdit"
                                 class="nav-link">
                                  <i class="fa fa-plus"></i>Ajouter
                              </a>
                          </li>
                      </ul>
                  </li>

                  <li class="nav-item">
                      <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                          <a class="d-flex align-items-center text-muted">Blocs</a>
                      </h6>
                      <ul class="list-unstyled" id="programs-submenu">
                          <li class="nav-item">
                              <a asp-area="Admin" asp-controller="Blocks" asp-action="List"
                                 class="nav-link">
                                  <i class="fa fa-list"></i>Lister
                              </a>
                          </li>
                          <li class="nav-item">
                              <a asp-area="Admin" asp-controller="Blocks" asp-action="GetEdit"
                                 class="nav-link">
                                  <i class="fa fa-plus"></i>Ajouter
                              </a>
                          </li>
                      </ul>
                  </li>

                  <li class="nav-item">

                      <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                          <a class="d-flex align-items-center text-muted">Clients</a>
                      </h6>
                      <ul class="list-unstyled" id="programs-submenu">
                          <li class="nav-item">
                              <a asp-area="Admin" asp-controller="Client" asp-action="List"
                                 class="nav-link">
                                  <i class="fa fa-list"></i>Lister
                              </a>
                          </li>
                          <li class="nav-item">
                              <a asp-area="Admin" asp-controller="Client" asp-action="GetEdit"
                                 class="nav-link">
                                  <i class="fa fa-plus"></i>Ajouter
                              </a>
                          </li>
                      </ul>
                  </li>

                  <li class="nav-item">
                      <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                          <a class="d-flex align-items-center text-muted">Programmes</a>
                      </h6>
                      <ul class="list-unstyled" id="programs-submenu">
                          <li class="nav-item">
                              <a asp-area="Admin" asp-controller="Programs" asp-action="List"
                                 class="nav-link">
                                  <i class="fa fa-list"></i>Lister
                              </a>
                          </li>
                          <li class="nav-item">
                              <a asp-area="Admin" asp-controller="Programs" asp-action="GetEdit"
                                 class="nav-link">
                                  <i class="fa fa-plus"></i>Ajouter
                              </a>
                          </li>
                      </ul>
                  </li>

                  <li class="nav-item">
                      <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                          <a class="d-flex align-items-center text-muted">Email</a>
                      </h6>
                      <ul class="list-unstyled" id="programs-submenu">
                          <li class="nav-item">
                              <a asp-area="Admin" asp-controller="MailBox" asp-action="Index"
                                 class="nav-link">
                                  <i class="fa fa-envelope-o"></i> Email
                              </a>
                          </li>
                      </ul>
                  </li>

</div>
    </div>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
        <h3>@ViewData["PageName"]</h3>
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3">
            @RenderBody()
        </div>
            @if (IsSectionDefined("Scripts"))
            {
                @RenderSection("Scripts", required: true)
            }
    </main>
</body>
</html>